version: '2.1'
services:
  ruby:
    build:
      context: .
      dockerfile: Dockerfile
    command: rails s
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mappd_development
    ports:
      - "5432:5432"
